// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-rLOcasbJ_hDJ92CrYRxF_CE9MCTeWZs',
    appId: '1:824652252881:web:733e3228dc1b7f2144a7f0',
    messagingSenderId: '824652252881',
    projectId: 'sample-project-19ca2',
    authDomain: 'sample-project-19ca2.firebaseapp.com',
    storageBucket: 'sample-project-19ca2.appspot.com',
    measurementId: 'G-VG0GC00F1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6R3beXg506AH7oODUGrpqdfninM6X034',
    appId: '1:824652252881:android:1a64849cca97cbf744a7f0',
    messagingSenderId: '824652252881',
    projectId: 'sample-project-19ca2',
    storageBucket: 'sample-project-19ca2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJrqph1l3hA9tX8byzQwpP-JnrgK1wrbg',
    appId: '1:824652252881:ios:87fdef648614a84344a7f0',
    messagingSenderId: '824652252881',
    projectId: 'sample-project-19ca2',
    storageBucket: 'sample-project-19ca2.appspot.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJrqph1l3hA9tX8byzQwpP-JnrgK1wrbg',
    appId: '1:824652252881:ios:027cde895a03449444a7f0',
    messagingSenderId: '824652252881',
    projectId: 'sample-project-19ca2',
    storageBucket: 'sample-project-19ca2.appspot.com',
    iosBundleId: 'com.example.firebaseTest.RunnerTests',
  );
}
